### ISSUE TITLE
works with typescript?

### ISSUE THREAD

**Issue by Rxbzey** [JesusAguilarAliaga/react-extract-colors#1]
theres  @types install for this ?

**Comment by jesus-aguiIar** [comment]
> theres @types install for this ?

Hello, this hook is currently only created in JavaScript. I am working on rewriting everything in TypeScript. However, if you want to use it in TypeScript, you can create a file in the root of your project named "index.d.ts" and include the following code:
```js 
declare module 'react-extract-colors' {
    export function useExtractColor(imageUrl: string, optionsCustom?: Record<string, any>): {
      dominantColor: string | null;
      darkerColor: string | null;
      lighterColor: string | null;
      loading: boolean;
      error: Error | null;
      colors: string[];
    };
  }
  ```
